export enum ERol
{
  ADMIN="ADMIN",
  VALIDA_ALUMNO = "VALIDA_ALUMNO",
  VALIDA_CURSO = "VALIDA_CURSO",
  VALIDA_PLANTEL = "VALIDA_PLANTEL",
  VALIDA_DOCENTE = "VALIDA_DOCENTE",
  DOCENTE = "DOCENTE",
  ALUMNO = "ALUMNO",
  CONTROL_ESCOLAR = "CONTROL_ESCOLAR",
  COORDINADOR_ACADEMICO = "COORDINADOR_ACADEMICO",
  PLANTEL="PLANTEL",
  OFERTA_EDUCATIVA="OFERTA_EDUCATIVA",
  // ADMIN_FINANZAS="ADMIN_FINANZAS",
}
